
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_ORGANIZATION" ("ORGANIZATION_ID", "STENO", "NAME", "TYPEORGANISATION", "WEBSITE", "DESCRIPTION", "FOUNDED", "INDUSTRY", "CAREEL", "CAPLAFOND", "HOLDINGMANAGER", "LATITUDE", "LONGITUDE", "COUNTRYID") AS 
  SELECT 
    o.ORGANIZATION_ID,
    o.STENO,
    o.NAME,
    o.TYPEORGANISATION,
    o.WEBSITE,
    o.DESCRIPTION,
    o.FOUNDED,
    o.INDUSTRY,
    o.CAREEL,
    o.CAPLAFOND,
    o.HOLDINGMANAGER,
    o.LATITUDE,
    o.LONGITUDE,
    o.COUNTRYID
FROM ORGANIZATION o
LEFT JOIN COUNTRY c ON o.COUNTRYID = c.COUNTRYID;