create or replace TRIGGER "TRG_CONTRAT_MAJ_CA_ORGANISATION"
AFTER INSERT OR UPDATE OR DELETE ON "CONTRAT"
FOR EACH ROW
DECLARE
    v_orgid ORGANIZATION.ORGANIZATION_ID%TYPE;
    v_delta NUMBER;
BEGIN
    IF INSERTING THEN
        v_orgid := :NEW.ORGANIZATIONID;
        v_delta := :NEW.MONTANT;

    ELSIF DELETING THEN
        v_orgid := :OLD.ORGANIZATIONID;
        v_delta := -:OLD.MONTANT;

    ELSIF UPDATING THEN
        v_orgid := :NEW.ORGANIZATIONID;
        v_delta := :NEW.MONTANT - :OLD.MONTANT;
    END IF;

    UPDATE ORGANIZATION
    SET CAREEL = CAREEL + v_delta
    WHERE ORGANIZATION_ID = v_orgid;
END;
/