
  CREATE TABLE "CLIENT" 
   (	"CLIENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NUMCLIENT" NUMBER NOT NULL ENABLE, 
	"NOM" VARCHAR2(100) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(150), 
	"TELEPHONE" VARCHAR2(20), 
	 PRIMARY KEY ("CLIENT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_CLIENT_NUMCLIENT" UNIQUE ("NUMCLIENT")
  USING INDEX  ENABLE
   ) ;