
  CREATE TABLE "CONTRAT" 
   (	"CONTRATID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NUMCONTRAT" NUMBER NOT NULL ENABLE, 
	"CLIENTID" NUMBER NOT NULL ENABLE, 
	"ORGANIZATIONID" NUMBER NOT NULL ENABLE, 
	"DATECONTRAT" DATE NOT NULL ENABLE, 
	"LIBELLE" VARCHAR2(200), 
	"MONTANT" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("CONTRATID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_CONTRAT_NUMCONTRAT" UNIQUE ("NUMCONTRAT")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CONTRAT" ADD CONSTRAINT "FK_CONTRAT_CLIENT" FOREIGN KEY ("CLIENTID")
	  REFERENCES "CLIENT" ("CLIENT_ID") ENABLE;
  ALTER TABLE "CONTRAT" ADD CONSTRAINT "FK_CONTRAT_ORGANIZATION" FOREIGN KEY ("ORGANIZATIONID")
	  REFERENCES "ORGANIZATION" ("ORGANIZATION_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CONTRAT_MAJ_CA_ORGANISATION" 
AFTER INSERT OR UPDATE OR DELETE ON "CONTRAT"
FOR EACH ROW
DECLARE
    v_orgid ORGANIZATION.ORGANIZATION_ID%TYPE;
    v_delta NUMBER;
BEGIN
    IF INSERTING THEN
        v_orgid := :NEW.ORGANIZATIONID;
        v_delta := :NEW.MONTANT;

    ELSIF DELETING THEN
        v_orgid := :OLD.ORGANIZATIONID;
        v_delta := -:OLD.MONTANT;

    ELSIF UPDATING THEN
        v_orgid := :NEW.ORGANIZATIONID;
        v_delta := :NEW.MONTANT - :OLD.MONTANT;
    END IF;

    UPDATE ORGANIZATION
    SET CAREEL = CAREEL + v_delta
    WHERE ORGANIZATION_ID = v_orgid;
END;
/
ALTER TRIGGER "TRG_CONTRAT_MAJ_CA_ORGANISATION" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CONTRAT_MONTANT" 
before
insert or update on "CONTRAT"
for each row
begin
    IF :NEW.MONTANT <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Le montant du contrat doit etre positif');
    END IF;
end;
/
ALTER TRIGGER "TRG_CONTRAT_MONTANT" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_HIST_CONTRAT" 
after
insert or update or delete on "CONTRAT"
for each row
DECLARE 
    v_action VARCHAR2(10);
    v_old VARCHAR2(4000);
    v_new VARCHAR2(4000);
begin
    IF INSERTING THEN
    v_action := 'INSERT';
    v_new := 'NumContrat=' || :NEW.NumContrat || ', Montant=' || :NEW.Montant;
  ELSIF UPDATING THEN
    v_action := 'UPDATE';
    v_old := 'NumContrat=' || :OLD.NumContrat || ', Montant=' || :OLD.Montant;
    v_new := 'NumContrat=' || :NEW.NumContrat || ', Montant=' || :NEW.Montant;
  ELSIF DELETING THEN
    v_action := 'DELETE';
    v_old := 'NumContrat=' || :OLD.NumContrat || ', Montant=' || :OLD.Montant;
  END IF;

  INSERT INTO HISTORIQUE_AFFAIRE (Utilisateur, AncienneValeur, NouvelleValeur, Action)
  VALUES (NVL(V('APP_USER'), USER), v_old, v_new, v_action);
end;
/
ALTER TRIGGER "TRG_HIST_CONTRAT" ENABLE;