
  CREATE TABLE "COUNTRY" 
   (	"COUNTRYID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"LIBELLE" VARCHAR2(60) NOT NULL ENABLE, 
	 PRIMARY KEY ("COUNTRYID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_COUNTRY_LIBELLE" UNIQUE ("LIBELLE")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_COUNTRY_DELETE" 
before
insert or update or delete on "COUNTRY"
for each row
DECLARE
    v_nb NUMBER;
begin
    SELECT COUNT(*) INTO v_nb FROM ORGANIZATION WHERE COUNTRYID = :OLD.COUNTRYID;
    IF v_nb > 0 THEN 
        RAISE_APPLICATION_ERROR(-20003, 'Impossible de supprimer un pays qui est utilise');
    END IF;
end;
/
ALTER TRIGGER "TRG_COUNTRY_DELETE" ENABLE;