
  CREATE TABLE "ORGANIZATION" 
   (	"ORGANIZATION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"STENO" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"TYPEORGANISATION" VARCHAR2(20), 
	"WEBSITE" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(200), 
	"FOUNDED" NUMBER(4,0), 
	"INDUSTRY" VARCHAR2(100), 
	"CAREEL" NUMBER DEFAULT 0, 
	"CAPLAFOND" NUMBER, 
	"HOLDINGMANAGER" VARCHAR2(50), 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	"COUNTRYID" NUMBER, 
	 PRIMARY KEY ("ORGANIZATION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_ORGANIZATION_STENO" UNIQUE ("STENO")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "ORGANIZATION" ADD CONSTRAINT "FK_ORGANIZATION_COUNTRY" FOREIGN KEY ("COUNTRYID")
	  REFERENCES "COUNTRY" ("COUNTRYID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ORGANIZATION_CA" 
before
insert or update  on "ORGANIZATION"
for each row
begin
    IF :NEW.CAREEL > :NEW.CAPLAFOND THEN
        RAISE_APPLICATION_ERROR(-20005, 'Le chiffres d affaires reel ne peut pas etre superieur au chiffre d affaires maximal');
    END IF;
end;
/
ALTER TRIGGER "TRG_ORGANIZATION_CA" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ORGANIZATION_DELETE" 
before
delete on "ORGANIZATION"
for each row
DECLARE
    v_nb NUMBER;
begin
    SELECT COUNT(*) INTO v_nb FROM CONTRAT WHERE ORGANIZATIONID = :OLD.ORGANIZATION_ID;
    IF v_nb > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Impossible de supprimer une organisation avec au moins un contrat');
    END IF;
    
end;
/
ALTER TRIGGER "TRG_ORGANIZATION_DELETE" ENABLE;